### ISSUE TITLE
Feature Request: Provide view distance sliders in Framework Settings

### ISSUE THREAD

**Issue by bentc123** [unitedoperations/UnitedOperationsFramework#103]
#### Feature Intent

Mission maker should be able to change view distances for AI/players.

#### Possible Implementation

Sliders in 'UO Framework' > 'Framework Settings' below 'Team Settings' section to adjust AI and player view distances.

**Comment by thecogdoctor** [comment]
Addressed and introduced in #104.

Thanks for the request!
