### ISSUE TITLE
Feature request: Make extraction end condition independent of other end conditions.

### ISSUE THREAD

**Issue by Aphex123** [unitedoperations/UnitedOperationsFramework#110]
#### Feature Intent

Extraction should not require other conditions to be met.

#### Possible Implementation

Extraction should work like any other end condition. 
Current implementation restricts MM in how they can use extraction.

Example that is not possible currently: Having team sneak through AO to extract zone without regard for casualties or anything else.

**Comment by ChrSacher** [comment]
Implemented in  PR #108

**Comment by thecogdoctor** [comment]
Reopened until fix is merged and tested.

**Comment by thecogdoctor** [comment]
Added and functional in #113.
