### ISSUE TITLE
Feature request: Individual unit babel settings.

### ISSUE THREAD

**Issue by Aphex123** [unitedoperations/UnitedOperationsFramework#111]
#### Feature Intent

Individual units should be able to speak different language than just their side.

#### Possible Implementation

Add a text box in unit ACRE settings to set a babel language for that unit. Will be in addition of side babel settings.

#### Additional notes

Example use: MM wants an interpreter on blufor that can communicate with opfor.

**Comment by ChrSacher** [comment]
Addressed in #113

**Comment by thecogdoctor** [comment]
Added in #113.
