### ISSUE TITLE
Bug Report: JIP module causes script error on opening ACE interact

### ISSUE THREAD

**Issue by Artur-Laskowski** [unitedoperations/UnitedOperationsFramework#125]
#### Description of issue

JIPing makes ACE interact unavailable

#### Logs

``21:57:16 Error in expression <le ["UO_FW_SpawnPos", (getpos player)]) > (_this select 0))}, {}, [_distance]] c>
21:57:16   Error position: <> (_this select 0))}, {}, [_distance]] c>
21:57:16   Error >: Type Object, expected Number,Not a Number
21:57:16 File \x\UO_FW\addons\Main\Core\cfgFunctions\JIP\fn_GiveActions.sqf [UO_FW_fnc_JIP_GiveActions], line 1921``

#### Mission File(s)

`TVT42_Pillar_of_Ohmen_V2`

#### Steps to reproduce

Add the steps needed to reproduce the issue. For example:

1. JIP into a in-progress mission.
2. Try to open self interact.
3. Notice above error.

#### Expected behaviour

No script errors.

#### Video and Screenshots

nil

#### Additional context

nil

**Comment by TrainDoctor** [comment]
Video and screenshots would be very helpful.
Please also include the RPT regardless.

**Comment by ChrSacher** [comment]
Issue has been found and will be fixed.

**Comment by TrainDoctor** [comment]
This should be addressed once #124 is merged to dev.

**Comment by TrainDoctor** [comment]
Fixed in #124.
