### ISSUE TITLE
EG Spectator

### ISSUE THREAD

**Issue by burn0ut7** [unitedoperations/UnitedOperationsFramework#132]
[EG Spectator uses a hit EH to detect to the last killer if the unit dies to ace bleeding](https://github.com/unitedoperations/UnitedOperationsFramework/blob/7f57249a13f4c3129c8688d2cb35fa0cb75ff6eb/uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_HitHandler.sqf). This is not needed and is [already incorporated into ace](https://github.com/acemod/ACE3/issues/3790#issuecomment-219654741).

`_unit getVariable ["ace_medical_lastDamageSource", _killer];`

The EH hit and its use should be converted to use ace's built in solution.

**Comment by TrainDoctor** [comment]
While this is good to know, this doesn't fall under a feature request or a bug report.
At this time we have no intention of changing the system for the time being unless it is changed through a pull-request.

Thanks for the heads-up.

**Comment by TrainDoctor** [comment]
Looking into making an adjustment to the system which uses the ACE variable you mentioned. If you could file this as a full feature request with any specific details of how you feel the system should be modified would be helpful.

**Comment by TrainDoctor** [comment]
In a TBD commit to a feature specific branch of experimental, I'll look into using this suggested change.

**Comment by ChrSacher** [comment]
We will take a look at it

**Comment by ChrSacher** [comment]
Implemented in PR#134 .

Thanks for telling us.
