### ISSUE TITLE
Feature Request: ACE carry/drag option and weight adjustment attributes 

### ISSUE THREAD

**Issue by TheLocalPub** [unitedoperations/UnitedOperationsFramework#19]
ACE has documentation that outlines how to add carry and/or drag options to items.
Currently tho, any item you can move via interaction has a weight and over a certain amount the said item cannot be moved due to being to heavy.

The weight of an object can quite easily be adjusted via the objects init by placing the following which is from one of my missions where a HMG box **was** to heavy to move but now is moveable.
`ACE_maxWeightDrag = 10000; 
this setVariable ["ACE_maxWeightDrag", 10000];`

Is there a possibility of adding a sliding bar in the attributes of items/objects which would allow for ease of weight adjustment.
One bar that represents the carry weight and another for the drag weight.
It would make for an easier time when it came to adjust said stuff instead of having to figure out the above init code.

https://ace3mod.com/wiki/framework/dragging-framework.html

**Comment by thecogdoctor** [comment]
Should be a quick addition. I'll aim have it integrated at least into a testing version soon™️.

**Comment by thecogdoctor** [comment]
![image](https://user-images.githubusercontent.com/11465594/48668094-c02ef980-ea99-11e8-9c51-0e844741db1a.png)
Implemented, now for testing!

**Comment by thecogdoctor** [comment]
Alright, after some testing it seems that would be best integrated into our custom version of ACE3. My own version is inconsistent and doesn't appear to function as intended no matter how I configure it. @Reyfin go ahead and mark this issue as not-applicable. Apologies.

**Comment by PiZZAD0X** [comment]
I think its a global var not a unit variable... So it would either be a setting globally across all units and capable objects or an ability to do some script that hooks the ace carry/drag system which I'm sure someone else has done before.

**Comment by thecogdoctor** [comment]
> I think its a global var not a unit variable... So it would either be a setting globally across all units and capable objects or an ability to do some script that hooks the ace carry/drag system which I'm sure someone else has done before.

I've used these variables myself and can confirm they are per object/unit not global. Global would cause all kinds issues.

**Comment by PiZZAD0X** [comment]
Are you sure about that? The weight limitations in ACE seem to be set through a missionnamespace var... https://github.com/acemod/ACE3/blob/a357675ad3445459a020acaeeac9d8663ee21c63/addons/dragging/functions/fnc_startCarry.sqf#L25

**Comment by thecogdoctor** [comment]
> 
> 
> Are you sure about that? The weight limitations in ACE seem to be set through a missionnamespace var... https://github.com/acemod/ACE3/blob/a357675ad3445459a020acaeeac9d8663ee21c63/addons/dragging/functions/fnc_startCarry.sqf#L25

Well then you've got me there, last time I used it I could swear it was a per object attribute but I stand corrected.
And after multiple attempts at implementing the requested feature I'm going to have to back down from this as the multiple different attempts I've made to get something like this functioning via UOFW.

**Comment by PiZZAD0X** [comment]
If you put those var defines in a unit/object init it could set the global
var on a SP session which is probably how you got those effects. It could
still be made into a global setting for the weight limits. Or a
modification of our custom ace

**Comment by thecogdoctor** [comment]
I was informed that our version of ACE3 is simply kept so we can update ACE as we see fit to prevent changes to ACE causing issues with key and mod verification. You would need to talk to a GSO, likely impulse about adding custom features to our version of ACE3.
