### ISSUE TITLE
PBOs in repo and build/deploy system approach

### ISSUE THREAD

**Issue by thecogdoctor** [unitedoperations/UnitedOperationsFramework#21]
Inclusion of PBOs in the repository is un-needed and can be provided through the releases/tags system on major version changes.
And less pressing but semi-important for other users being able to build the framework themselves quickly, I highly recommend build and deploy are modified to be multi-system compatible.
```BAT
"C:\Program Files\PBO Manager v.1.4 beta\PBOConsole.exe" -pack "C:\Users\Christian\Documents\Arma 3 Projects\UnitedOperationsFramework\UnitedOperationsFramework" "C:\Users\Christian\Documents\Arma 3 Projects\UnitedOperationsFramework\UnitedOperationsFramework.pbo"
xcopy "C:\Users\Christian\Documents\Arma 3 Projects\UnitedOperationsFramework\UnitedOperationsFramework.pbo" "C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@UOF\addons\" /Y
pause
```
Would become,
```BAT
set "build_exe_loc=C:\Program Files\PBO Manager v.1.4 beta"
set /P use_directory=[Build in a different directory? (y/n)]
set "
if /I "%use_directory%"=="y" ( set /P build_directory=[Specify a directory: ] )
if /I "%use_directory%"=="n" ( set build_directory=%CD% )
if not defined use_directory (set use_directory=n)
"%build_exec_loc%\PBOConsole.exe" -pack "%build_directory%" "%build_directory%\UnitedOperationsFramework.pbo"
pause
```
Etc.

**Comment by Reyfin** [comment]
You can allways make a pull request

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/UnitedOperationsFramework/pull/4/commits/ad0fc667e3e99f9c43706dc7acd5a3ea109423c2 You can test out a dynamic build bat on my fork

**Comment by PiZZAD0X** [comment]
https://github.com/unitedoperations/UnitedOperationsFramework/pull/29

**Comment by thecogdoctor** [comment]
Have not had the ability to fully test the functionality of this code but, from what I can tell this code should be fully functional.<br/>We should definitely consider multi-platform support later down the line (Linux and macOS compilation etc).

Secondly, the inclusion of the compiled PBO outside of the releases/tags section seems a tad strange, backup pbo not withstanding. I am willing to take on the responsibilities surrounding the releases section as needed.
