### ISSUE TITLE
Ability to add custom brief

### ISSUE THREAD

**Issue by TheLocalPub** [unitedoperations/UnitedOperationsFramework#25]
Just how you can link to a custom end conditions file, could we please be capable of doing the same for brief?

**Comment by PiZZAD0X** [comment]
Can you not already? That functionality was added when the module was written, let us know if it isn't working.
https://github.com/unitedoperations/UnitedOperationsFramework/blob/6887acd3efdfd1a4699e3b52bad29493e72e1343/UnitedOperationsFramework/BriefingModule/cfg3DEN/Briefing/Blufor.hpp#L732

**Comment by Reyfin** [comment]
I am using it in my missions and it works fine.
