### ISSUE TITLE
Feature Request: Wave & triggered respawns, spectator interrupt/cancel function, settings

### ISSUE THREAD

**Issue by PiZZAD0X** [unitedoperations/UnitedOperationsFramework#26]
#### Feature Intent

-Add the ability for the mission maker to add wave respawns that require a certain number of players to be dead before spawning reinforcements.
-Add the ability for dead/spectating players to be respawned after a function/publicvariable is called serverside.
-Add the ability for the mission maker to tailor the spectate settings. (whitelisted sides, enabled view modes, etc) Reference: https://github.com/dklollol/Olsen-Framework-Arma-3/blob/2bd64721703dc143db0feae45ad51b63f319ceda/modules/eg_spectator_mode/settings.sqf

#### Screenshots

nil.

#### Possible Implementation

-Add an interrupt in the spectate function.
-Add a function that remoteExec's respawning/exiting spectator for the dead players. Reference: https://github.com/dklollol/Olsen-Framework-Arma-3/blob/2bd64721703dc143db0feae45ad51b63f319ceda/modules/eg_spectator_mode/init.sqf#L169

#### Additional notes
 
nil.

**Comment by thecogdoctor** [comment]
Closed until this feature is addressed as exploring or in progress etc.
