### ISSUE TITLE
Feature Request: Export/Import settings

### ISSUE THREAD

**Issue by PiZZAD0X** [unitedoperations/UnitedOperationsFramework#32]
#### Feature Intent

Add the ability to save/load presets for mission settings via profileNamespace. 

#### Screenshots

nil

#### Possible Implementation

Separate menu on the UO Framework editor tab. You cannot dynamically add menus, but we can create a dialog that could read those settings. An array of [PresetName,SettingArray] should suffice. 

#### Additional notes

nil.

**Comment by PiZZAD0X** [comment]
R3vo is working on export/import functions now in 3den enhanced so this feature will be unnecessary unless you guys think that hardcoded UO_FW settings are a good idea or someone can think of a good additional feature. R3vo's video previewing the feature: https://www.youtube.com/watch?v=SCmSZ0GQqbE

**Comment by thecogdoctor** [comment]
I noticed that this feature was moved to the "needs testing" column. @PiZZAD0X, is this feature ready for testing withing a main release or is this feature at a stage where general editor testing is still needed?

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/UnitedOperationsFramework/commit/d1c9bc244d0b5d4b20cf4da13796ddc93a3791d0

Over on the headless branch on my fork.
