### ISSUE TITLE
Feature Request: Ported/Unported Modules Index

### ISSUE THREAD

**Issue by thecogdoctor** [unitedoperations/UnitedOperationsFramework#36]
### Intent

To serve as an index of completed and to-be-completed/ported modules from the Olsen framework into the UOFW.

### Index
Completed | Incomplete/Unported
------------ | -------------
| AI Drivers | ace_medical |
| AO Limit Soft and Hard | AI Attack * |
| AI Link | AI Skill |
| Anti ND | Ambient Animation |
| Auto Track | Ambient Effects |
| Capture Zone | Call Mission |
| Cover Map | cvc_check ** |
| Firemission | env_parameters |
| Disconnect Control | extract |
| Hostage Module | gas_script |
| Join in Progress | Plank * |
| Marker Control | Radio Messages * |
| Safe Start | Random Scenario* |
| Self Actions | Self Actions |
| Setup Timer | start_on_safe *** (Anti ND) |
| Shot Count | Task Control * |
| Start in Parachute |  |
| Start Text | |
| Gear Functionality | |
| Team Color Assignment | |
| Briefing | |
| Map & Compass Remover | |

- Priority unknown:  *
- Low priority: **
- Integrate into a different module: ***

#### New Additions
- @PiZZAD0X Style Headless AI Client  

#### Planned Additions
- @thecogdoctor addRack for ACRE module. 
- @thecogdoctor advanced actions module

#### Good potential additions
- [drosfeh's](https://github.com/dklollol/Olsen-Framework-Arma-3/pull/200) conversion of gear script functionality to using params
  - (If this has not already been changed in a similar form.)
- [drosfeh's](https://github.com/dklollol/Olsen-Framework-Arma-3/pull/200) addItemRandomPercent
  - (We need to give it a different name if we do add it though...) 

### Possible Implementation

On a per module basis.
- TBD
- TBD

### Additional notes

If you have any suggestions to add to this index please leave them here.

**Comment by PiZZAD0X** [comment]
https://github.com/unitedoperations/UnitedOperationsFramework/projects/5
