### ISSUE TITLE
Request: CBA Compliance

### ISSUE THREAD

**Issue by thecogdoctor** [unitedoperations/UnitedOperationsFramework#37]
## Intent

- All modules not yet included or in development should be CBA compliant or made to be ASAP.
- All currently present modules should at some point be reviewed and made to be CBA compliant. 

#### Quick definition of some important terminology;

- **CBA Compliant**, compliance etc: Using the standards for contribution used by the CBA, ACE3 and ACRE2 teams.
- **Standards** for compliance: When I say compliance, I am referring to the [**guidelines**](http://acre2.idi-systems.com/wiki/development/coding-guidelines-sqf) of the ACRE2 developers. 
  - These guidelines are the best way to accomplish CBA compliance. It lists in great detail the contribution standards for ACRE2, many of these are reflective of the more "unwritten" standards used in CBA and ACE3.
- **"The big three"** and other similar terms: Simply refers to ACE3, ACRE2 and CBA.

#### What x does not mean:
- **CBA Compliant**: This does not mean 100% adherence to say, the code formatting guidelines/requirements of CBA, ACE3 or ACRE2.
  - (Although that would be delightful.) 

#### What x does mean:
- **CBA Compliant**: Largely equal usage of standards used by ACRE2 for contribution. 
  - The UOFW when it is fully compliant will have it's compliance standards still within the overall boundaries defined by the ACRE2 documentation. 
  - Changes to suit the nature of the project and it's contributors preferences will be inevitable and supported.
  - This also means that homegrown solutions should meet the standards of code found in the big three. The review process will determine the standards for homegrown solutions over time.
  - Full and proper usage of CBA macros, functionality and more instead of using techniques which stray outside of the purview of CBA unless this new addition is made to be a homegrown addition that is from the get-go, compliant.

## Reasoning

I am proposing this requirement for full CBA compliance (eventually) as it will ensure this code-base is:</br> (Sorted by priority/importance)
1. **Favor from ACE3 and CBA communities.** 
    - UOFW will be more likely to receive contributions and even more likely, peer review by the CBA and ACE3 communities. 
    - UOFW must be put into the public eye in order to accomplish this as a whole, but this compliance ensures compatibility and expertise are more available and likely to contribute to UOFW.
2. **Better and more readable code.**
     - Use of CBA means that we are not relying upon extremely processor taxing techniques to accomplish certain functionality. etc
     - Quality control for code and the other elements of the UOFW which would be inherited from CBA compliance.
     - This would also include a review process that ensures CBA compatibility and compliance for each new module and contributions of different natures.
3. Longevity.
4. Usability.
    - Compliance means that the UOFW is likely to be picked up by many communities new and even old as time goes on.

#### Transitioning (Pre-processing)

1. All contributors and collaborators will be asked to read and review CBA macros, functions and standards. 
    - While not a forced requirement for any previous contributors or collaborators, this will be required for future contributions.
2. Review of current modules and suggestions to ensure compliance. 
    - I have spoken with a interested party from the ACE3 community in regards to help with a potential transition to CBA compliance.
3. Implementation process, detailed below.

#### After transition (Processing and post-processing)

1. Begin moving all current systems over to the usage of CBA macros and the other various elements that comprise CBA compliance. 
2. Ensure compliance of all incoming modules and or contributions to the UOFW.
    -  Again, the UOFW will be held to standards adapted from ACRE2's documentation as it is the most fleshed out project in regards to detailing the nature of compliance with CBA.
3. ???
4. Benefit!

#### Example Module

WIP. Reference will be attached when fully functional and usable as an example for other modules.

#### Author's note:

I understand that compliance will feel like a large undertaking, but it is much easier than you would think.
I am currently working on an example of a CBA compliant UOFW module. The module will be fully compliant but has a few extra parts to ensure the previous system will still be able to use the new compliant modules without the full transition to compliance meaning a total destruction of all previously existing code simply to accomplish compliance. Please leave feedback and suggestions. While I feel this may be viewed as a hail-mary, the implications of this request could mean the project's longevity will extend beyond even the current contributors roles in the project in the long run.

**Comment by PiZZAD0X** [comment]
https://github.com/unitedoperations/UnitedOperationsFramework/projects/5

Improved/Rewritten category
