### ISSUE TITLE
Port Request: ACE Medical Module

### ISSUE THREAD

**Issue by thecogdoctor** [unitedoperations/UnitedOperationsFramework#38]
#### Feature Intent

Port functionality of Olsen Framework ace_medical module.
Alternatively, make setting per mission medical settings more clear to newer mission makers or those who have never bothered to touch the medical settings in their missions.

#### Screenshots

Nil.

#### Possible Implementation

3 Major options, all of which can be combined if desired.

- Module
- In Editor Tutorial/example
- Documentation in Editor or wiki on how to change per mission medical settings.

#### Additional notes

This Port Request is an unported module of the Olsen Framework which is a part of [#36 Ported/Unported Modules Index](https://github.com/unitedoperations/UnitedOperationsFramework/issues/36)

**Comment by PiZZAD0X** [comment]
Aren't all mission ace medical settings handled by CBA?

**Comment by thecogdoctor** [comment]
> 
> 
> Aren't all mission ace medical settings handled by CBA?

They are indeed handled through CBA settings. I will be closing this issue but we should ensure that mission-makers are made aware of how to customize per-mission medical settings.
