### ISSUE TITLE
Feature Request: Allow Administrators to use menu to adjust mission time, safe start, and control respawns

### ISSUE THREAD

**Issue by JudahHarvey** [unitedoperations/UnitedOperationsFramework#63]
#### Feature Intent

An Administrative control panel that would allow game masters and sever admins without script knowledge to control the flow of missions even without zeus intervention. This menu should be out of the way, not require the use of scripts, and allow admins to see pertinent information.

## Admins should be able to see

- Total Team Tickets remaining
- Total Time Remaining for mission before end condition.
- End Condition status.

## Admins should be able to influence using a menu (Preferably in the map screen)
Adjust mission time by adding or reducing time
Add or reduce Individual/Team tickets to allow respawns or force wave respawns.
Induce a Wave respawn to bring all dead players back into game at the starting area from spectator.

**Comment by thecogdoctor** [comment]
@JudahHarvey I do agree such a feature would be advantageous but this framework was originally designed to work inside of the United Operations modpack. 
Our current focus is testing and refinement of the current modules at this moment in time.

This of course, is not to say that this is an impossible request but it is also straying towards out of the framework's scope as a mission making tool.

We will look into a way of implementing this at some point in the future if we determine this falls within the scope of the framework.

**Comment by JudahHarvey** [comment]
What is the mod for that admin console?

**Comment by thecogdoctor** [comment]
https://github.com/unitedoperations/uo_debugconsole

**Comment by PiZZAD0X** [comment]
debug console needs updating to call correct mission end, extend time limit, time limit display, etc...

**Comment by thecogdoctor** [comment]
This feature falls under the scope of a different addon. We may consider it for a public release.
