### ISSUE TITLE
Area Scaling Widget does not work on Following Modules

### ISSUE THREAD

**Issue by JudahHarvey** [unitedoperations/UnitedOperationsFramework#68]
#### Area Scaling Widget does not work on Following Modules
AO Limit Module (Rect, ellipse) 
Capture Module (Rect, ellipse) 
Cover Map Module
Setup Timer Module (Rect, ellipse) 
AI Control (Rect, ellipse) 
AI Zone (Rect, ellipse) 

Add a clear and concise description of the error. This makes it easier for us to fix the issue.
Area Scaling widget should function like it does on triggers, 

#### Steps to reproduce
Place any UO module down and try and use area scaling widget (4 key), to expand it. 
The radius will expand and then snap back to the values entered in the radius X, Y fields. 
Try it with a trigger or something from BI and it works fine.

#### Expected behaviour

The trigger should expand, and the radius X and Y values should follow what was set with the widget
#### Screenshots

![107410_20190304210004_1](https://user-images.githubusercontent.com/16574249/53775431-8a831480-3ec0-11e9-82d7-4619a15829ff.png)

#### Modlist
* CBA A3
* ACE 3
* ACRE2
* UOFW

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/UnitedOperationsFramework/commit/6bfb3059c8accc0d3ad64ca373ca6a34e8283b62
