### ISSUE TITLE
Documentation Request: Custom End-Conditions from Olsen Framework

### ISSUE THREAD

**Issue by TrainDoctor** [unitedoperations/UnitedOperationsFramework#76]
#### Documentation Intent

This guide should add a full guide for changing custom end-conditions from the Olsen Framework to United Operations Framework end-condition calls.

#### Resources

[Functions that can be used to determine End-Conditions](https://github.com/unitedoperations/UnitedOperationsFramework/tree/master/uo_sys_framework/Core/cfgFunctions/common)

#### Possible Implementation

N/A

#### Additional notes

N/A

**Comment by PiZZAD0X** [comment]
I was going to say that we could largely copy a guide to writing olsen end conditions... but I can't even find one haha. No wonder people have issues with them.

**Comment by TrainDoctor** [comment]
All documentation related tasks have been moved to trello. This issue will be marked as completed once done on trello.
