### ISSUE TITLE
Bug Report: Mission Notes tab does not appear

### ISSUE THREAD

**Issue by Nathan423** [unitedoperations/UnitedOperationsFramework#98]
#### Description of issue

When Missions notes are added, they do not appear in the mission. The mission was created with 1.0.2 (I believe) and the latest test was with 1.0,4.

#### Logs

https://pastebin.com/3aR8Bzb8

#### Mission File(s)

[CO10_General_Distress_V1.Tanoa.zip](https://github.com/unitedoperations/UnitedOperationsFramework/files/3036359/CO10_General_Distress_V1.Tanoa.zip)

#### Steps to reproduce

* Open mission created in earlier version of UOF
* Create "Mission Notes" under the appropriate window.
* Load SP, Local MP, or dedicated MP
* Question life

#### Expected behaviour

A "Mission Notes" tab appear with appropriate information supplied by the mission maker.

#### Video and Screenshots

N/A

#### Additional context

N/A

**Comment by PiZZAD0X** [comment]
Mission Notes var was changed. but older settings still apply to the new var value. 
![Screenshot_329](https://user-images.githubusercontent.com/11909749/55445701-74c14780-5571-11e9-967d-84d3f6e05354.png)

**Comment by Nathan423** [comment]
Another issue I found with this is that the Author shows as a tester and the tester(s) show as the author.

**Comment by thecogdoctor** [comment]
> 
> 
> Another issue I found with this is that the Author shows as a tester and the tester(s) show as the author.

Fixed in a recent commit to my fork. Will be making a PR soon™️.

**Comment by thecogdoctor** [comment]
Multiple fixes for issues related to the & symbol being used in briefings found. These have been resolved but yet to be tested on my dev branch.

**Comment by PiZZAD0X** [comment]
> 
> 
> Multiple fixes for issues related to the & symbol being used in briefings found. These have been resolved but yet to be tested on my dev branch.

In user input or in our functions?

**Comment by thecogdoctor** [comment]
In our functions.

**Comment by PiZZAD0X** [comment]
"Command & Signals" works fine being added by the function, what is the issue from the use of &? I believe it is only an issue when you add it directly opposed to a structured text format. 
![Screenshot_330](https://user-images.githubusercontent.com/11909749/55514179-4a789400-561c-11e9-888f-82a3e3e61677.png)

**Comment by thecogdoctor** [comment]
```sqf
_enStr = _enStr + "<font color='#5BD527' size='14.0'><h1>Probable Enemy Artillery Positions & Capability:</h1></font color><br/>" + _enArty;
```
This is the line I found in all briefings that encountered the issue. BriefingModule/defines/xyz_briefing.hpp
